"""empty message

Revision ID: 58282015b884
Revises: bbf1ac38151d
Create Date: 2023-04-11 12:17:35.681436

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '58282015b884'
down_revision = 'bbf1ac38151d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=50), nullable=True))
        batch_op.drop_column('subscribed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscribed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('location')

    # ### end Alembic commands ###
