"""empty message

Revision ID: bbf1ac38151d
Revises: 2e4220df56eb
Create Date: 2023-04-11 12:04:35.701529

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bbf1ac38151d'
down_revision = '2e4220df56eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_table('order',
    #sa.Column('id', sa.Integer(), nullable=False),
    #sa.Column('total', sa.Integer(), nullable=True),
    #sa.PrimaryKeyConstraint('id')
    #)
    #op.drop_table('orders')
    op.rename_table('orders', 'order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_table('orders',
    #sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    #sa.Column('total', mysql.INTEGER(), autoincrement=False, nullable=True),
    #sa.PrimaryKeyConstraint('id'),
    #mysql_collate='utf8mb4_0900_ai_ci',
    #mysql_default_charset='utf8mb4',
    #mysql_engine='InnoDB'
    #)
    #op.drop_table('order')
    op.rename_table('order', 'orders')
    # ### end Alembic commands ###
