"""empty message

Revision ID: 152ffabc36b0
Revises: 550dcb56b2b0
Create Date: 2023-04-20 12:22:30.993683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '152ffabc36b0'
down_revision = '550dcb56b2b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
