"""empty message

Revision ID: 550dcb56b2b0
Revises: cb9389e5e189
Create Date: 2023-04-19 15:07:52.411982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550dcb56b2b0'
down_revision = 'cb9389e5e189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=140), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tweet')
    # ### end Alembic commands ###
